// Language.swift
import Foundation

struct Language: Identifiable, Equatable {
    let id = UUID()
    let code: String
    let name: String
    let flag: String
    
    // Khởi tạo danh sách ngôn ngữ hỗ trợ
    static let supportedLanguages: [Language] = [
        Language(code: "en", name: "English", flag: "🇺🇸"),
        Language(code: "vi", name: "Tiếng Việt", flag: "🇻🇳"),
        Language(code: "es", name: "Español", flag: "🇪🇸"),
        Language(code: "fr", name: "Français", flag: "🇫🇷"),
        Language(code: "de", name: "Deutsch", flag: "🇩🇪"),
        Language(code: "ja", name: "日本語", flag: "🇯🇵"),
        Language(code: "ar", name: "العربية", flag: "🇸🇦"),
        Language(code: "pt", name: "Português", flag: "🇵🇹"),
        Language(code: "ru", name: "Русский", flag: "🇷🇺"),
        Language(code: "zh", name: "中文", flag: "🇨🇳"),
        Language(code: "it", name: "Italiano", flag: "🇮🇹"),
        Language(code: "ko", name: "한국어", flag: "🇰🇷"),
        Language(code: "tr", name: "Türkçe", flag: "🇹🇷"),
        Language(code: "nl", name: "Nederlands", flag: "🇳🇱"),
        Language(code: "pl", name: "Polski", flag: "🇵🇱"),
        Language(code: "id", name: "Bahasa Indonesia", flag: "🇮🇩"),
        Language(code: "ms", name: "Bahasa Melayu", flag: "🇲🇾"),
        Language(code: "th", name: "ไทย", flag: "🇹🇭"),
        Language(code: "hi", name: "हिन्दी", flag: "🇮🇳"),
        Language(code: "ur", name: "اردو", flag: "🇵🇰"),
        Language(code: "fa", name: "فارسی", flag: "🇮🇷"),
        Language(code: "he", name: "עברית", flag: "🇮🇱"),
        Language(code: "bn", name: "বাংলা", flag: "🇧🇩"),
        Language(code: "ro", name: "Română", flag: "🇷🇴"),
        Language(code: "uk", name: "Українська", flag: "🇺🇦"),
        Language(code: "sv", name: "Svenska", flag: "🇸🇪"),
        Language(code: "da", name: "Dansk", flag: "🇩🇰"),
        Language(code: "no", name: "Norsk", flag: "🇳🇴"),
        Language(code: "fi", name: "Suomi", flag: "🇫🇮"),
        Language(code: "cs", name: "Čeština", flag: "🇨🇿"),
        Language(code: "hu", name: "Magyar", flag: "🇭🇺"),
        Language(code: "el", name: "Ελληνικά", flag: "🇬🇷"),
        Language(code: "sk", name: "Slovenčina", flag: "🇸🇰"),
        Language(code: "mk", name: "Македонски", flag: "🇲🇰"),
        Language(code: "sr", name: "Српски", flag: "🇷🇸"),
        Language(code: "hr", name: "Hrvatski", flag: "🇭🇷"),
        Language(code: "sq", name: "Shqip", flag: "🇦🇱"),
        Language(code: "bg", name: "Български", flag: "🇧🇬"),
        Language(code: "ka", name: "ქართული", flag: "🇬🇪"),
        Language(code: "bs", name: "Bosanski", flag: "🇧🇦"),
        Language(code: "sm", name: "Samoan", flag: "🇼🇸"),
        Language(code: "sw", name: "Kiswahili", flag: "🇰🇪"),
        Language(code: "lv", name: "Latviešu", flag: "🇱🇻"),
        Language(code: "lt", name: "Lietuvių", flag: "🇱🇹"),
        Language(code: "sl", name: "Slovenščina", flag: "🇸🇮"),
        Language(code: "mt", name: "Malti", flag: "🇲🇹"),
        Language(code: "is", name: "Isländska", flag: "🇮🇸"),
        Language(code: "mn", name: "Монгол", flag: "🇲🇳"),
        Language(code: "kk", name: "Қазақ", flag: "🇰🇿"),
        Language(code: "az", name: "Azərbaycan dili", flag: "🇦🇿"),
        Language(code: "hy", name: "Հայերեն", flag: "🇦🇲"),
        Language(code: "uz", name: "O'zbek", flag: "🇺🇿"),
        Language(code: "tk", name: "Türkmençe", flag: "🇹🇲"),
        Language(code: "rw", name: "Kinyarwanda", flag: "🇷🇼"),
        Language(code: "so", name: "Somali", flag: "🇸🇴"),
        Language(code: "am", name: "አማርኛ", flag: "🇪🇹"),
        Language(code: "my", name: "မြန်မာဘာသာ", flag: "🇲🇲"),
        Language(code: "ky", name: "Кыргызча", flag: "🇰🇬"),
        Language(code: "si", name: "සිංහල", flag: "🇱🇰"),
        Language(code: "st", name: "Sesotho", flag: "🇸🇹"),
        Language(code: "ny", name: "Chichewa", flag: "🇲🇼"),
        Language(code: "ga", name: "Gaeilge", flag: "🇮🇪"),
        Language(code: "to", name: "Tongan", flag: "🇹🇴"),
        Language(code: "fj", name: "Fijian", flag: "🇫🇯"),
        Language(code: "bi", name: "Bislama", flag: "🇻🇺"),
        Language(code: "gm", name: "Gambian", flag: "🇬🇲"),
        Language(code: "pap", name: "Papiamento", flag: "🇦🇼"),
        Language(code: "tpi", name: "Tok Pisin", flag: "🇵🇬"),
        Language(code: "ts", name: "Xitsonga", flag: "🇿🇦"),
        Language(code: "sn", name: "Shona", flag: "🇿🇼"),
        Language(code: "ss", name: "Siswati", flag: "🇸🇿")
    ]
}
